---
- name: Install transmission packages
  ansible.builtin.package:
    name: "{{ transmission_packages }}"
    state: present

- block:
  - name: Check if log file exists
    ansible.builtin.stat:
      path: "{{ transmission_logfile }}"
    register: __logfile
  - name: Create log file
    ansible.builtin.file:
      path: "{{ transmission_logfile }}"
      state: touch
      owner: "{{ transmission_user }}"
      mode: 0600
    when: not __logfile.stat.exists
  when: transmission_logfile | length > 0

- name: Configure transmission systemd service
  ansible.builtin.template:
    src: usr/lib/systemd/system/transmission-daemon.service
    dest: /usr/lib/systemd/system/transmission-daemon.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload transmission-daemon

- name: Enable and start transmission service
  ansible.builtin.systemd:
    name: transmission-daemon
    state: started
    enabled: true
  when: transmission_enable | bool
